name: Release

on:
  push:
    tags: ['*.*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: BoxOUtils
          path: build/libs
      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: Reports
          path: build/reports
      - name: Get Version
        id: get-version
        uses: battila7/get-version-action@v2
      - name: Create a Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Box O' Utils ${{ github.ref }}
          draft: true
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./build/libs/BoxOUtils-${{ steps.get-version.outputs.version-without-v }}.jar
          asset_name: BoxOUtils-${{ steps.get-version.outputs.version-without-v }}.jar
          asset_content_type: application/java-archive
